// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pttotqqkhaxozkrznsun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0dG90cXFraGF4b3prcnpuc3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzk3MDIsImV4cCI6MjA3MTkxNTcwMn0.WA5PieReU-0SpUBVxvqIWGi23GWLqEbtXqrYNsWwJwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});